const { Property } = require("../models");

module.exports = async () => {
  try {
    await Property.bulkCreate([
      {
        name: "Stone and Adobe Oasis",
        description:
          "In the midst of the Tulor oasis, this organic, self-sustaining stone and adobe house boasts a cozy interior design. With four levels, including a tower and walkable roof, it offers unparalleled views of the Salar de Atacama, the Cordillera de la Sal, and the Licancabur volcano. An ideal place to rest, enjoy the silence, and stargaze. Close to Laguna Cejar and Valle de la Luna.",
        propertyType: "house",
        capacity: 6,
        pricePerNight: 200,
        address: "Oasis Street",
        phone: "+598 12345678",
        country: "Uruguay",
        rating: 9,
        availableDateFrom: new Date("2024-09-01"),
        availableDateTo: new Date("2024-09-15"),
        amenities: {
          beds: 6,
          bathrooms: 2,
          parking: true,
          breakfast: false,
          airConditioning: true,
        },
      },
      {
        name: "Atacama Hotel Retreat",
        description:
          "Experience the ultimate luxury at this boutique hotel nestled in the heart of the Atacama Desert. Immerse yourself in comfort and style while enjoying breathtaking views of the surrounding landscapes. Indulge in gourmet meals and relax by the poolside oasis. Perfect for a romantic getaway or a serene retreat.",
        propertyType: "hotel",
        capacity: 2,
        pricePerNight: 500,
        address: "Desert Oasis Road",
        phone: "+56 298765432",
        country: "Chile",
        rating: 10,
        availableDateFrom: new Date("2024-10-01"),
        availableDateTo: new Date("2024-10-15"),
        amenities: {
          beds: 1,
          bathrooms: 1,
          parking: true,
          breakfast: true,
          airConditioning: true,
        },
      },
      {
        name: "Luxury Beachfront Villa",
        description:
          "Escape to paradise in this luxurious beachfront villa. Enjoy stunning ocean views, private beach access, and world-class amenities. Perfect for a family vacation or romantic getaway.",
        propertyType: "house",
        capacity: 8,
        pricePerNight: 600,
        address: "Beachfront Avenue",
        phone: "+1 3105550123",
        country: "USA",
        rating: 9,
        availableDateFrom: new Date("2024-08-01"),
        availableDateTo: new Date("2024-08-15"),
        amenities: {
          beds: 4,
          bathrooms: 4,
          parking: true,
          breakfast: false,
          airConditioning: true,
        },
      },
      {
        name: "City Center Loft",
        description:
          "Experience urban living at its finest in this stylish city center loft. Modern design, panoramic city views, and proximity to top attractions make it the perfect choice for your next city break.",
        propertyType: "apartment",
        capacity: 4,
        pricePerNight: 250,
        address: "Downtown Street",
        phone: "+44 2012345678",
        country: "UK",
        rating: 8,
        availableDateFrom: new Date("2024-09-01"),
        availableDateTo: new Date("2024-09-15"),
        amenities: {
          beds: 2,
          bathrooms: 2,
          parking: false,
          breakfast: false,
          airConditioning: true,
        },
      },
      {
        name: "Mountain View Cabin",
        description:
          "Experience tranquility in this charming cabin nestled in the heart of the mountains. Surrounded by nature, with hiking trails right outside your door, it's the perfect retreat for outdoor enthusiasts.",
        propertyType: "house",
        capacity: 4,
        pricePerNight: 150,
        address: "Mountain Retreat Road",
        phone: "+33 123456789",
        country: "France",
        rating: 9,
        availableDateFrom: new Date("2024-10-01"),
        availableDateTo: new Date("2024-10-15"),
        amenities: {
          beds: 4,
          bathrooms: 2,
          parking: true,
          breakfast: false,
          airConditioning: false,
        },
      },
      {
        name: "Riverside Cottage",
        description:
          "Unwind in this cozy riverside cottage surrounded by lush greenery. Fish in the nearby river, relax in the garden, or explore the charming village nearby. A perfect escape from the hustle and bustle of city life.",
        propertyType: "house",
        capacity: 2,
        pricePerNight: 100,
        address: "Riverside Lane",
        phone: "+49 3012345678",
        country: "Germany",
        rating: 8,
        availableDateFrom: new Date("2024-11-01"),
        availableDateTo: new Date("2024-11-15"),
        amenities: {
          beds: 1,
          bathrooms: 1,
          parking: true,
          breakfast: false,
          airConditioning: false,
        },
      },
      {
        name: "Seaside Retreat",
        description:
          "Relax and rejuvenate at this stunning seaside retreat. Enjoy panoramic ocean views, private beach access, and luxurious amenities. Perfect for a romantic getaway or family vacation.",
        propertyType: "house",
        capacity: 6,
        pricePerNight: 400,
        address: "Seaside Drive",
        phone: "+61 212345678",
        country: "Australia",
        rating: 9,
        availableDateFrom: new Date("2024-12-01"),
        availableDateTo: new Date("2024-12-15"),
        amenities: {
          beds: 3,
          bathrooms: 2,
          parking: true,
          breakfast: false,
          airConditioning: true,
        },
      },
      {
        name: "Ski Chalet",
        description:
          "Experience the ultimate winter getaway in this cozy ski chalet. Located near the slopes, with ski-in/ski-out access, it's perfect for avid skiers and snowboarders. After a day on the slopes, relax by the fireplace and enjoy stunning mountain views.",
        propertyType: "house",
        capacity: 8,
        pricePerNight: 300,
        address: "Ski Lodge Lane",
        phone: "+1 6041234567",
        country: "Canada",
        rating: 8,
        availableDateFrom: new Date("2025-01-01"),
        availableDateTo: new Date("2025-01-15"),
        amenities: {
          beds: 4,
          bathrooms: 3,
          parking: true,
          breakfast: false,
          airConditioning: false,
        },
      },
      {
        name: "Zen Garden Oasis",
        description:
          "Find inner peace at this tranquil Zen garden oasis. Surrounded by lush greenery and soothing water features, it's the perfect retreat for relaxation and meditation.",
        propertyType: "house",
        capacity: 4,
        pricePerNight: 300,
        address: "Zen Garden Lane",
        phone: "+81 312345678",
        country: "Japan",
        rating: 9,
        availableDateFrom: new Date("2025-04-01"),
        availableDateTo: new Date("2025-04-15"),
        amenities: {
          beds: 4,
          bathrooms: 2,
          parking: true,
          breakfast: false,
          airConditioning: true,
        },
      },
      {
        name: "Treehouse Haven",
        description:
          "Escape to this enchanting treehouse haven nestled in the forest canopy. Experience the magic of living among the trees, with panoramic views and nature-inspired decor.",
        propertyType: "house",
        capacity: 2,
        pricePerNight: 200,
        address: "Treehouse Retreat Road",
        phone: "+1 2061234567",
        country: "USA",
        rating: 8,
        availableDateFrom: new Date("2025-05-01"),
        availableDateTo: new Date("2025-05-15"),
        amenities: {
          beds: 1,
          bathrooms: 1,
          parking: false,
          breakfast: false,
          airConditioning: false,
        },
      },
      {
        name: "Urban Loft Retreat",
        description:
          "Experience modern luxury in this stylish urban loft retreat. Located in the heart of the city, with sleek design and city views, it's perfect for cosmopolitan travelers.",
        propertyType: "apartment",
        capacity: 4,
        pricePerNight: 300,
        address: "Urban Loft Avenue",
        phone: "+1 2121234567",
        country: "USA",
        rating: 9,
        availableDateFrom: new Date("2025-08-01"),
        availableDateTo: new Date("2025-08-15"),
        amenities: {
          beds: 2,
          bathrooms: 2,
          parking: false,
          breakfast: false,
          airConditioning: true,
        },
      },
      {
        name: "Boutique Guesthouse",
        description:
          "Indulge in luxury at this boutique guesthouse. With personalized service, elegant decor, and exclusive amenities, it offers a refined retreat for discerning travelers.",
        propertyType: "guesthouse",
        capacity: 6,
        pricePerNight: 600,
        address: "Boutique Guesthouse Street",
        phone: "+33 123456789",
        country: "France",
        rating: 9,
        availableDateFrom: new Date("2025-09-01"),
        availableDateTo: new Date("2025-09-15"),
        amenities: {
          beds: 6,
          bathrooms: 4,
          parking: true,
          breakfast: false,
          airConditioning: true,
        },
      },
      {
        name: "Sunny Beach House",
        description:
          "Relax in style at this beautiful beach house. With direct beach access, spacious interiors, and stunning ocean views, it's the perfect getaway for sun seekers.",
        propertyType: "house",
        capacity: 8,
        pricePerNight: 500,
        address: "Sunny Beach House Street",
        phone: "+1 3051234567",
        country: "USA",
        rating: 9,
        availableDateFrom: new Date("2026-07-01"),
        availableDateTo: new Date("2026-07-15"),
        amenities: {
          beds: 4,
          bathrooms: 3,
          parking: true,
          breakfast: false,
          airConditioning: true,
        },
      },
      {
        name: "Downtown Loft",
        description:
          "Experience urban living at its best in this chic downtown loft. Located in the heart of the city, with modern design and city views, it's perfect for city explorers.",
        propertyType: "apartment",
        capacity: 2,
        pricePerNight: 250,
        address: "Downtown Loft Avenue",
        phone: "+44 2012345678",
        country: "UK",
        rating: 8,
        availableDateFrom: new Date("2026-08-01"),
        availableDateTo: new Date("2026-08-15"),
        amenities: {
          beds: 1,
          bathrooms: 1,
          parking: false,
          breakfast: false,
          airConditioning: true,
        },
      },
      {
        name: "Cozy Guesthouse Retreat",
        description:
          "Escape to this charming guesthouse retreat surrounded by nature. With cozy interiors, tranquil surroundings, and personalized hospitality, it's the perfect home away from home.",
        propertyType: "guesthouse",
        capacity: 6,
        pricePerNight: 300,
        address: "Cozy Guesthouse Retreat Lane",
        phone: "+33 123456789",
        country: "France",
        rating: 9,
        availableDateFrom: new Date("2026-09-01"),
        availableDateTo: new Date("2026-09-15"),
        amenities: {
          beds: 3,
          bathrooms: 2,
          parking: true,
          breakfast: false,
          airConditioning: false,
        },
      },
      {
        name: "Luxury Hotel Suite",
        description:
          "Indulge in luxury at this exquisite hotel suite. With elegant furnishings, top-notch amenities, and impeccable service, it offers a truly unforgettable stay.",
        propertyType: "hotel",
        capacity: 4,
        pricePerNight: 600,
        address: "Luxury Hotel Suite Boulevard",
        phone: "+61 212345678",
        country: "Australia",
        rating: 10,
        availableDateFrom: new Date("2026-10-01"),
        availableDateTo: new Date("2026-10-15"),
        amenities: {
          beds: 2,
          bathrooms: 2,
          parking: true,
          breakfast: true,
          airConditioning: true,
        },
      },
    ]);
    console.log("Properties were created successfully");
  } catch (error) {
    console.error("Error creating properties", error);
  }
};
